---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfreconfig-mcp-server
rules:
  # CAPI Clusters
  - apiGroups: ["cluster.x-k8s.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "watch"]
  
  # Repositories (Porch/Nephio)
  - apiGroups: ["config.porch.kpt.dev", "porch.kpt.dev"]
    resources: ["repositories"]
    verbs: ["get", "list", "watch"]
  
  # Secrets (for kubeconfig access)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  
  # Network resources
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ["network-attachment-definitions"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: ["workload.nephio.org"]
    resources: ["nfconfigs", "nfdeployments"]
    verbs: ["get", "list", "watch"]
  
  # Cluster info (Nodes, ConfigMaps for CIDR extraction)
  - apiGroups: [""]
    resources: ["nodes", "configmaps"]
    verbs: ["get", "list"]
  
  # Workload resources (for workload tools)
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "delete"]
  
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "delete"]
  
  # ArgoCD Applications
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch", "patch", "update"]
  
  # Generic resource access for dynamic queries
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nfreconfig-mcp-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfreconfig-mcp-server
subjects:
  - kind: ServiceAccount
    name: nfreconfig-mcp-server
    namespace: kagent
